/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jnidemo_demo_com_jnidemo_MainActivity */

#ifndef _Included_jnidemo_demo_com_jnidemo_MainActivity
#define _Included_jnidemo_demo_com_jnidemo_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jnidemo_demo_com_jnidemo_MainActivity
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jnidemo_demo_com_jnidemo_MainActivity_getStringFromNative
        (JNIEnv *env, jobject jobject1){
    char *str = "Hello JNI!";
    return (*env)->NewStringUTF(env, str);

}

#ifdef __cplusplus
}
#endif
#endif
